i=int(input("enter the interger  :"))
s=input("enter the string : ")
f=float(input("enter the float value: "))
b=bool(input("enter the boolean number :"))
c= complex(input("enter  the complex number :"))
print(type(i))
print(type(s))
print(type(f))
print(type(b))
print(type(c))